name: Setup auth
inputs:
  environment:
    description: "what environment to deploy for (dev / prod)"
    required: true
  tailscale_id:
    description: "Tailscale OAuth Client ID"
    required: true
  tailscale_secret:
    description: "Tailscale OAuth Secret"
    required: true
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true

runs:
  using: composite
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Set up Depot CLI
      uses: depot/setup-action@v1
