name: Setup auth
inputs:
  service:
    description: 'Service to deploy'
    required: true
  deploy_key:
    description: 'SSH deploy key'
    required: true
  manifests_repo:
    description: 'Manifests repository'
    required: true
  values_file_name:
    description: 'Values file name'
    required: true
  modified_values:
    description: 'Modified values'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout manifests repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.manifests_repo }}
        ssh-key: ${{ inputs.deploy_key }}
        path: manifests
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.deploy_key }}
    - name: Install yq
      shell: bash
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
    - name: Update Helm values
      shell: bash
      run: |
        SERVICE_NAME=${{ inputs.service }}
        IMAGE_TAG=${{ github.sha }}
        cd manifests/$SERVICE_NAME

        json_string="${{ inputs.modified_values }}"
        json_string=$(echo $json_string | sed "s/'/\"/g")

        # Generate update commands from JSON
        updates=$(echo $json_string | yq -r e -f json '. | to_entries | .[] | .key + " |= \"" + .value + "\""' -o json)

        # Apply each update command to the YAML file
        echo "$updates" | while read -r update; do
            if [[ ! -z "$update" ]]; then
                echo $update
                yq e -i "$update" ${{ inputs.values_file_name }}
            fi
        done

        git config --global user.name "deployooooooooor[bot]"
        git config --global user.email "deployooooooooor[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update $SERVICE_NAME image to $IMAGE_TAG"
        git push git@github.com:skip-mev/slinky-manifests main
    # - name: Update Helm values
    #   if: github.event.client_payload.environment == 'prod'
    #   run: |
    #     SERVICE_NAME=${{ github.event.client_payload.service }}
    #     IMAGE_TAG=${{ github.event.client_payload.tag }}
    #     cd $SERVICE_NAME
    #     yq eval ".image.tag = \"$IMAGE_TAG\"" -i values.yaml
    # - name: Create Pull Request
    #   id: cpr
    #   uses: peter-evans/create-pull-request@v6
    #   if: github.event.client_payload.environment == 'prod'
    #   with:
    #     commit-message: Promote ${{ github.event.client_payload.service }} to ${{ github.event.client_payload.tag }}
    #     committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
    #     author: ${{ github.event.sender }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
    #     branch: ${{ github.event.client_payload.environment }}-promote-${{ github.event.client_payload.service }}-${{ github.event.client_payload.tag }} 
    #     delete-branch: true
    #     title: '[Example] Update report'
    #     body: |
    #       Promoting versions to prod
    #       - Auto-generated by [create-pull-request][1]
    #
    #       [1]: https://github.com/peter-evans/create-pull-request
    #     labels: |
    #       automated pr
    #     draft: false
