name: Reusable docker build workflow
on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to build for'
        required: true
        type: string
      registry_url_suffix:
        description: 'The suffix for the registry URL'
        required: true
        type: string
      tailscale_id:
        description: 'Tailscale ID for the build'
        required: true
        type: string
      tailscale_secret:
        description: 'Tailscale secret for the build'
        required: true
        type: string
      aws_access_key_id:
        description: 'AWS Access Key ID for ECR access'
        required: true
        type: string
      aws_secret_access_key:
        description: 'AWS Secret Access Key for ECR access'
        required: true
        type: string

jobs:
  build:
    # TODO: what about different environments?
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup the pipeline
        uses: ./.github/actions/setup
        with:
          environment: ${{ inputs.environment }}
          tailscale_id: ${{ secrets.tailscale_id }}
          tailscale_secret: ${{ secrets.tailscale_secret }}
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          ecr_url_prefix: ${{ secrets.ecr_url_prefix }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if it does not exist
        run: |
          aws ecr describe-repositories --region us-east-2 --repository-names $repo_name || aws ecr create-repository --repository-name $repo_name --region us-east-2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
        with:
          images: |
            ${{ secrets.ecr_url_prefix}}/${{ inputs.registry_url_suffix }}
          tags: |
            type=sha,priority=900,prefix=
            type=semver,priority=1000,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr

      - uses: cloudposse/github-action-matrix-outputs-write@v1
        id: out
        with:
          matrix-step-name: github-action-matrix-outputs-read
          matrix-key: ${{ matrix.builds.image }}
          outputs: |-
            version: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
            tag: ${{ steps.meta.outputs.version }}