name: Reusable docker build workflow
on:
  workflow_call:
    inputs:
      image_name:
        description: 'The name of the image to build'
        required: true
        type: string
      matrix_key:
        description: 'The key for the matrix'
        required: true
        type: string
      docker_file_path:
        description: 'The Dockerfile to use for the build'
        required: true
        type: string

jobs:
  build:
    runs-on: depot-ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Show inputs
        run: |
          echo "Inputs:"
          echo "  image_name: ${{ inputs.image_name }}"
          echo "  matrix_key: ${{ inputs.matrix_key }}"
          echo "  docker_file_path: ${{ inputs.docker_file_path }}"

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-session-name: ${{ github.ref_name }}-build-dev
          role-to-assume: arn:aws:iam::494494944992:role/GithubImagePusher

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if it does not exist
        run: |
          aws ecr describe-repositories --region us-east-2 --repository-names ${{ inputs.image_name }} || aws ecr create-repository --repository-name ${{ inputs.image_name }} --region us-east-2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
        with:
          images: |
            ${{ secrets.ecr_url_prefix}}/${{ inputs.image_name }}
          tags: |
            type=sha,priority=900,prefix=
            type=semver,priority=1000,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Go Build Cache for Docker
        uses: actions/cache@v3
        with:
          path: go-build-cache
          key: ${{ runner.os }}-${{ inputs.matrix_key }}-go-build-cache-${{ hashFiles('**/go.sum') }}

      - name: inject go-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v2.1.2
        with:
          cache-source: go-build-cache

      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          context: .
          file: ${{ inputs.docker_file_path }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          project: "06dnhndwwg"
          push: true

      - name: Extract Docker version from tags
        id: extract
        shell: bash
        run: |
          echo "Meta output JSON:"
          echo '${{ steps.meta.outputs.json }}' > raw.json
          jq '.' raw.json

          version=$(jq -r '.tags[0]' raw.json)
          echo "version=$version" >> $GITHUB_OUTPUT

    outputs:
      docker_version: ${{ steps.extract.outputs.version }}
      docker_tag: ${{ steps.meta.outputs.version }}

  write:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Write matrix outputs
        uses: cloudposse/github-action-matrix-outputs-write@v1
        id: out
        with:
          matrix-step-name: build
          matrix-key: ${{ inputs.matrix_key }}
          outputs: |-
            version: ${{ needs.build.outputs.docker_version }}
            tag: ${{ needs.build.outputs.docker_tag }}

    outputs:
      version: ${{ fromJson(steps.out.outputs.result).version }}
      tag: ${{ fromJson(steps.out.outputs.result).tag }}